VSL-182:  Define styles in scss - Button, Link
DapperCollectives/VESSEL pull request #97
Opened 2022-09-08 17:41 UTC by linxiao-li

## Description

This pr defined and applied the default link style and the following button styles:
- primary
- secondary
- tertiary
- transparent
- border
- nav

## Demo / Test Result

A brief walkthrough

https://user-images.githubusercontent.com/7423845/189189721-1ebc891a-1617-4046-ac36-a3911f04ef1c.mov

2022-09-09 21:40 UTC, amyliu6 approved these changes

2022-09-09 23:31 UTC, KsenijaZivkovic commented
Some of the buttons from the new features are not styled correctly, for example:
Error modal:
<img width="434" alt="Screen Shot 2022-09-09 at 4 23 06 PM" src="https://user-images.githubusercontent.com/20346621/189458470-44a74b0a-6a8d-4b1a-8fc5-efc607a36f4e.png">
Success Modal for sending NFT:
<img width="431" alt="Screen Shot 2022-09-09 at 4 23 59 PM" src="https://user-images.githubusercontent.com/20346621/189458475-1bf17972-9082-4d09-b7d6-262eb5c38474.png">
Success Modal for sending Tokens:
<img width="431" alt="Screen Shot 2022-09-09 at 4 24 23 PM" src="https://user-images.githubusercontent.com/20346621/189458477-71fd728f-f633-4128-a01c-4667cdd539ae.png">

2022-09-09 23:31 UTC, KsenijaZivkovic requested changes
Please update the buttons on the error and success modals
Related to the comment from VSL-131: 
`Just a heads up, all the work around button UI probably need to be refactored into using the new UI system once VSL-182 is merged, I'll work with you to make the update.`
Buttons used in that PR will be refactored once this one is merged.
The rest is LGTM! 👍

2022-09-12 14:35 UTC, linxiao-li commented
@KsenijaZivkovic updated!

2022-09-12 20:21 UTC, KsenijaZivkovic approved these changes

2022-09-12 20:33 UTC, merged